import {test} from 'node:test';
import assert from 'node:assert/strict';
import {Miniflare} from 'miniflare';
import {build} from 'esbuild';
import {readFileSync,readdirSync} from 'node:fs';
test('real Worker D1/R2 archive: auth, atomic cooldown, full content, originals and failed storage',async()=>{
 const built=await build({stdin:{contents:`import {env} from 'cloudflare:workers';import {runSource} from './lib/site-collection';import {authorized} from './lib/github-oidc';import {GET as exportGet,POST as exportPost} from './app/api/export/route';import {GET as archiveGet} from './app/api/publications/[id]/route';import {readStoredDataset,getStoredRecord,withContent} from './lib/site-storage';export default {async fetch(request){const url=new URL(request.url);if(url.pathname.startsWith('/api/publications/'))return archiveGet(request,{params:Promise.resolve({id:url.pathname.split('/').at(-1)})});if(url.pathname==='/export')return request.method==='POST'?exportPost(request):exportGet(request);if(url.pathname==='/collect'){if(!await authorized(request))return new Response('Unauthorized',{status:401});return Response.json(await runSource('ministry'))}if(url.pathname==='/content'){const data=await readStoredDataset();return Response.json(await withContent(data.records[0]))}return Response.json(await readStoredDataset())}}`,resolveDir:process.cwd()},bundle:true,write:false,format:'esm',platform:'browser',external:['cloudflare:workers','node:crypto']});
 const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
 const jwk={...await crypto.subtle.exportKey('jwk',pair.publicKey),kid:'test',use:'sig',alg:'RS256'};
 const now=Math.floor(Date.now()/1000);const claims={iss:'https://token.actions.githubusercontent.com',aud:'https://edu.travishunting.com/api/collect',repository:'TravisHunting/EducationNewsHubNZ',repository_id:'1365497342',repository_owner_id:'58845455',workflow_ref:'TravisHunting/EducationNewsHubNZ/.github/workflows/collect.yml@refs/heads/main',ref:'refs/heads/main',repository_visibility:'public',event_name:'schedule',sub:'repo:TravisHunting/EducationNewsHubNZ:ref:refs/heads/main',iat:now,nbf:now-1,exp:now+300};
 const token=async(changes={})=>{const data=Buffer.from(JSON.stringify({alg:'RS256',kid:'test'})).toString('base64url')+'.'+Buffer.from(JSON.stringify({...claims,...changes})).toString('base64url');return data+'.'+Buffer.from(await crypto.subtle.sign('RSASSA-PKCS1-v1_5',pair.privateKey,new TextEncoder().encode(data))).toString('base64url')};
 let blocked=false;let calls=0;const finalParagraph='FINAL PARAGRAPH beyond the old snippet boundary. ## Source reuse notes and more complete content.';
 const html='<html><body><h1>Education policy changes for all learners</h1><main><p>'+('Complete evidence. '.repeat(300))+'</p><p>'+finalParagraph+'</p><a href="/report.pdf">Whole report</a></main></body></html>';
 const mf=new Miniflare({modules:true,script:built.outputFiles[0].text,compatibilityDate:'2026-05-22',compatibilityFlags:['nodejs_compat'],d1Databases:['DB'],r2Buckets:['BUCKET'],outboundService:async request=>{const url=new URL(request.url);if(url.hostname==='token.actions.githubusercontent.com')return Response.json({keys:[jwk]});calls++;if(blocked)return new Response('Unavailable',{status:503});if(url.pathname==='/robots.txt')return new Response('User-agent: *\nAllow: /',{headers:{'Content-Type':'text/plain'}});if(url.pathname==='/news')return new Response('<main><a href="/news/whole-report">Education policy changes for all learners</a></main>',{headers:{'Content-Type':'text/html'}});if(url.pathname==='/report.pdf')return new Response('%PDF-1.7 complete file end %%EOF',{headers:{'Content-Type':'application/pdf'}});return new Response(html,{headers:{'Content-Type':'text/html'}})}});
 try{
  const db=await mf.getD1Database('DB');for(const name of readdirSync('drizzle').filter(x=>x.endsWith('.sql'))){for(const sql of readFileSync('drizzle/'+name,'utf8').split('--> statement-breakpoint')){if(sql.trim())await db.prepare(sql.trim()).run()}}
  await db.prepare('INSERT INTO collection_sources(id,next_allowed_at,state) VALUES (?,?,?)').bind('ministry',0,JSON.stringify({id:'ministry',checkedAt:new Date().toISOString(),status:'healthy',count:0,added:0,method:'test'})).run();
  assert.equal((await mf.dispatchFetch('https://test/collect',{method:'POST'})).status,401);assert.equal(calls,0);
  for(const changes of [{aud:'wrong'},{repository_id:'wrong'},{ref:'refs/heads/evil'},{exp:now-1},{event_name:'pull_request'},{repository_visibility:'private'}])assert.equal((await mf.dispatchFetch('https://test/collect',{method:'POST',headers:{Authorization:'Bearer '+await token(changes)}})).status,401);assert.equal(calls,0);
  const headers={Authorization:'Bearer '+await token()};
  const results=await Promise.all(Array.from({length:5},()=>mf.dispatchFetch('https://test/collect',{method:'POST',headers}).then(r=>r.json())));
  assert.equal(results.filter(r=>r.status==='cooldown').length,4);assert.equal(results.filter(r=>r.status==='healthy').length,1);assert.equal(calls,4);
  const data=await (await mf.dispatchFetch('https://test/')).json();assert.equal(data.records.length,1);assert.equal(data.records[0].content,undefined);
  const record=await (await mf.dispatchFetch('https://test/content')).json();assert.ok(record.content.includes(finalParagraph));assert.ok(record.content.length>5000);assert.equal(record.documents[0].status,'stored');
  for(const format of ['json','jsonl','markdown','csv']){const response=await mf.dispatchFetch('https://test/export?format='+format);assert.equal(response.status,200);const output=await response.text();assert.ok(output.includes(finalParagraph));if(format==='json'){const pack=JSON.parse(output);assert.equal(pack.manifest.recordCount,1);assert.equal(pack.records[0].content,record.content);assert.ok(pack.records[0].documents[0].archiveUrl)}}
  const selection=await (await mf.dispatchFetch('https://test/export?format=json',{method:'POST',body:JSON.stringify({ids:[]})})).json();assert.equal(selection.records.length,0);
  const raw=await mf.dispatchFetch('https://test/api/publications/'+record.id+'?format=html');assert.equal(raw.status,200);assert.match(raw.headers.get('Content-Disposition'),/attachment/);assert.equal(await raw.text(),html);
  const file=await mf.dispatchFetch('https://test/api/publications/'+record.id+'?document=0');assert.equal(await file.text(),'%PDF-1.7 complete file end %%EOF');
  const bucket=await mf.getR2Bucket('BUCKET');assert.equal(await (await bucket.get(record.htmlKey)).text(),html);assert.equal(await (await bucket.get(record.documents[0].storageKey)).text(),'%PDF-1.7 complete file end %%EOF');
  await db.prepare('UPDATE collection_sources SET next_allowed_at = 0').run();
  const again=await (await mf.dispatchFetch('https://test/collect',{method:'POST',headers})).json();assert.equal(again.status,'healthy');assert.equal((await (await mf.dispatchFetch('https://test/')).json()).records.length,1);
  await db.prepare('UPDATE collection_sources SET next_allowed_at = 0').run();blocked=true;assert.equal((await (await mf.dispatchFetch('https://test/collect',{method:'POST',headers})).json()).status,'error');assert.equal((await (await mf.dispatchFetch('https://test/content')).json()).content,record.content);assert.equal((await (await mf.dispatchFetch('https://test/collect',{method:'POST',headers})).json()).status,'cooldown');
 }finally{await mf.dispose()}
});
