export const TOPICS = ['Curriculum & assessment', 'Attendance & engagement', 'Workforce', 'Funding & policy', 'Learning support', 'Māori & Pacific', 'Early learning', 'Tertiary & skills', 'Research & evidence'];
export const SOURCES = [
  { id:'ministry', name:'Ministry of Education', short:'MOE', kind:'Government', url:'https://www.education.govt.nz/news', hosts:['www.education.govt.nz','education.govt.nz'], paths:['/news/'], description:'National education policy, school operations and ministry announcements.', policy:'Headline and short metadata excerpt. Original publication linked.' },
  { id:'ncea', name:'NCEA Education', short:'NCEA', kind:'Government', url:'https://ncea.education.govt.nz/whats-new', hosts:['ncea.education.govt.nz'], paths:['/whats-new/'], description:'Qualification reform, assessment changes and implementation updates.', policy:'Headline and short metadata excerpt. Original publication linked.' },
  { id:'counts', name:'Education Counts', short:'EC', kind:'Research', url:'https://www.educationcounts.govt.nz/publications', hosts:['www.educationcounts.govt.nz','educationcounts.govt.nz'], paths:['/publications/'], description:'Education research, achievement, participation and system statistics.', policy:'Publication metadata and links. Original datasets remain with the publisher.' },
  { id:'ero', name:'Education Review Office', short:'ERO', kind:'Research', url:'https://www.ero.govt.nz/', hosts:['www.ero.govt.nz','ero.govt.nz'], paths:['/about-us/news/'], description:'Independent evaluations and evidence on what works for learners.', policy:'Headline and short metadata excerpt. Original publication linked.' },
  { id:'nzqa', name:'NZ Qualifications Authority', short:'NZQA', kind:'Government', url:'https://www2.nzqa.govt.nz/about-us/news/', hosts:['www2.nzqa.govt.nz','www.nzqa.govt.nz'], paths:['/about-us/news/'], description:'Qualifications, assessment, quality assurance and learner guidance.', policy:'Headline and short metadata excerpt. Original publication linked.' },
  { id:'tec', name:'Tertiary Education Commission', short:'TEC', kind:'Government', url:'https://www.tec.govt.nz/news-and-consultations', hosts:['www.tec.govt.nz','tec.govt.nz'], paths:['/news-and-consultations/'], description:'Tertiary investment, vocational education and skills policy.', policy:'Headline and short metadata excerpt. Original publication linked.' },
  { id:'beehive', name:'Beehive · Education', short:'BEE', kind:'Government', url:'https://www.beehive.govt.nz/portfolio/education', hosts:['www.beehive.govt.nz','beehive.govt.nz'], paths:['/release/','/speech/'], description:'Ministerial education announcements and policy decisions.', policy:'Announcement metadata. Political claims are attributed to the publisher.' },
  { id:'rnz', name:'RNZ · Education', short:'RNZ', kind:'News', url:'https://www.rnz.co.nz/news/education', hosts:['www.rnz.co.nz','rnz.co.nz'], paths:['/news/education/'], description:'Independent reporting and perspectives from the education sector.', policy:'Discovery links and headlines only. Full articles are not copied.', metadataOnly:true },
  { id:'nzcer', name:'NZ Council for Educational Research', short:'NZCER', kind:'Research', url:'https://www.nzcer.org.nz/news-and-blogs', hosts:['www.nzcer.org.nz','nzcer.org.nz'], paths:['/news-and-blogs/'], description:'Independent education research, assessment evidence and practical insights for educators.', policy:'Headline and short public metadata only. Paywalled research is not collected.' },
];
